### ISSUE TITLE
missing lc_impact methods

### ISSUE THREAD

**Issue by Pommespapst** [cmutel/regionalized-lca-examples#1]
I cannot execute the code at
regionalized-lca-examples/LC-IMPACT-case-study/notebooks/2 - Set up regionalized
I get a NameError during step "Add regionalized LC IMPACT impact categories":

> Traceback (most recent call last):
  File "C:\Users\Pommespapst\Programs\Pycharm\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Users\Pommespapst\Programs\Pycharm\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Users\Pommespapst\Programs\Pycharm\PyCharm Community Edition 2018.3.5\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\Pommespapst\Programs\Pycharm\PyCharm Community Edition 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Pommespapst/PycharmProjects/BrightwayConda/main_regionalization_test.py", line 29, in <module>
    WaterEcosystemQualityCertain().import_regional_method()
NameError: name 'WaterEcosystemQualityCertain' is not defined

It seems, the following classes are not inlcuded in bw2-lcimpact version 0.1.1 (latest version on conda-forge):

WaterEcosystemQualityCertain
WaterEcosystemQualityAll
ParticulateMatterFormationAll
ParticulateMatterFormationCertain
LandUseOccupationMarginal
LandUseOccupationAverage
ClimateChangeHumanHealthCertain100Years
ClimateChangeHumanHealthAll100Years
ClimateChangeHumanHealthCertainInfinite
ClimateChangeHumanHealthAllInfinite
ClimateChangeTerrestrialEcosystemsCertain100Years
ClimateChangeTerrestrialEcosystemsAll100Years
ClimateChangeTerrestrialEcosystemsCertainInfinite
ClimateChangeTerrestrialEcosystemsAllInfinite
ClimateChangeAquaticEcosystemsAll100Years
ClimateChangeAquaticEcosystemsAllInfinite

**Comment by Pommespapst** [comment]
Fix:
Update bw2-lciimpact package. Type:
`conda install https://anaconda.org/cmutel/bw2_lcimpact/0.3/download/noarch/bw2_lcimpact-0.3-py_3.tar.bz2`
